### ISSUE TITLE
Input must be a vector, not a `tfd_reg/tfd/tf` object

### ISSUE THREAD

**Issue by andreasleha** [tidyfun/tidyfun#129] opened 2022-06-29 10:27 UTC
Hi all,

I am revisiting an old project using tidyfun.

This is the data

```
> mydat
# A tibble: 720 x 1
   pixel                             
   <tfd_reg>                         
 1 [1]: (-5,54);(-4,54);(-3,54); ... 
 2 [2]: (-5,28);(-4,28);(-3,28); ... 
 3 [3]: (-5,25);(-4,25);(-3,24); ... 
 4 [4]: (-5,50);(-4,50);(-3,50); ... 
 5 [5]: (-5,25);(-4,25);(-3,24); ... 
 6 [6]: (-5,24);(-4,24);(-3,23); ... 
 7 [7]: (-5, 0);(-4, 0);(-3, 0); ... 
 8 [8]: (-5,48);(-4,48);(-3,49); ... 
 9 [9]: (-5,40);(-4,41);(-3,41); ... 
10 [10]: (-5,37);(-4,36);(-3,36); ...
# … with 710 more rows
```

This used to work:

```
mydat %>% mutate(pixel = tf_zoom(pixel, 0, 10))
```

but now throws this error:

```
Error: Problem with `mutate()` input `pixel`.
✖ Input `pixel` must be a vector, not a `tfd_reg/tfd/tf` object.
ℹ Input `pixel` is `tf_zoom(pixel, 0, 10)`.
Run `rlang::last_error()` to see where the error occurred.
```

First question:
Is this still supposed to work?

If not, what am I supposed to do instead?

If yes, there seems to be a version conflict.

The installation of R (3.6.1) and tidyfun (0.0.82) have not changed in between, but dplyr has gone from 0.8.4 to 1.0.3.  There might have been other package updates, too.

I have not followed the development of tidyfun.  Am I supposed to update tidyfun now?  Do I have to expect many incompabilities?
(In the latter case it might be easier to try to recreate the environment with older (dplyr) versions.

Your help is highly appreciated.

**Comment by fabian-s** [comment] 2022-06-29 10:57
impossible to figure out what exactly the problem is without a proper reprex and detailed session info. 
i suspect the bug is due to the fact that dplyr now depends on proper `vctrs`-class definitions for non-standard column types, which @jeff-goldsmith added to tidyfun a while ago. 


it works fine for me 
```
> library(tidyfun); library(tidyverse)
> d <- tibble(f = tf_rgp(5))
> d |> mutate(f_z = tf_zoom(f, 0.3, 0.7))
# A tibble: 5 × 2
                                                 f                                              f_z
                                         <tfd_reg>                                        <tfd_reg>
1 [1]: (0.00, -1.4);(0.02, -1.3);(0.04, -1.2); ... [1]: (0.30, 0.68);(0.32, 0.86);(0.34, 0.98); ...
2 [2]: (0.00,-0.79);(0.02,-0.91);(0.04,-1.10); ... [2]: (0.30,-1.36);(0.32,-1.13);(0.34,-0.84); ...
3 [3]: (0.00,  1.5);(0.02,  1.6);(0.04,  1.5); ... [3]: (0.30, 1.13);(0.32, 0.99);(0.34, 0.97); ...
4 [4]: (0.00, -2.7);(0.02, -2.7);(0.04, -2.8); ... [4]: (0.30, -1.6);(0.32, -1.5);(0.34, -1.4); ...
5 [5]: (0.00, -1.2);(0.02, -1.1);(0.04, -1.1); ... [5]: (0.30,-0.48);(0.32,-0.52);(0.34,-0.51); ...
```
using more current versions of tidyfun with dplyr 1.0.9.

so: updating tidyfun (and your R version, we're at 4.2.1 now ...) is probably a good idea, the only breaking change in tidyfun *should* be in the geom_XXX functions, which no longer take a `y` aesthetic as the functional data input but `tf`.

**Comment by fabian-s** [comment] 2022-06-29 10:59
closing this since the problem is likely to be on your end, but please feel free to re-open it with a reproducible example and detailed session info if the problem continues to come up.

**Closed by fabian-s** 2022-06-29 10:59 UTC

**Comment by andreasleha** [comment] 2022-07-01 09:21
Just to say thanks.  Spot on.  Updating R was not an option, as tidyfun now depends on newer R.  After moving to a different machine with newer R and upgrading tidyfun, indeed, the only breaking change was the mentioned change in aes() of the geom_s.
